/**
 * WASM Web Worker
 * ================
 * 
 * This worker runs in a separate thread and handles all WASM processing.
 * This ensures the main thread (UI) remains responsive during heavy computation.
 * 
 * PRD Requirement (Section 4.1):
 * "All Wasm processing must occur in a Web Worker to prevent main thread freezing (60 FPS UI)"
 * 
 * Communication Protocol:
 * - Main thread sends: { type, id, payload }
 * - Worker responds: { type, id, payload?, error? }
 * - All responses use postMessage for async communication
 */

/// <reference lib="webworker" />

// Type declarations for worker context
declare const self: DedicatedWorkerGlobalScope;

// ============================================
// TYPE IMPORTS
// ============================================

import type {
    WasmWorkerRequestType,
    WasmWorkerResponse,
    WasmWorkerMessage,
    InitSuccessPayload,
    LoadImageSuccessPayload,
    RedactSuccessPayload,
    HashResultPayload,
    ImageInfoResultPayload,
    ResizeSuccessPayload,
    GrayscaleSuccessPayload,
    PiiResultPayload,
    ModuleInfoResultPayload,
    Box,
} from '../types/wasm-worker';

// ============================================
// WASM MODULE TYPES (from wasm-bindgen)
// ============================================

// These types are generated by wasm-bindgen
interface WasmModule {
    init(): void;
    is_initialized(): boolean;
    get_version(): string;
    get_module_info(): string;
    process_image(buffer: Uint8Array, width: number, height: number): Uint8Array;
    get_image_info(buffer: Uint8Array): string;
    get_dimensions(buffer: Uint8Array): string;
    redact_area(buffer: Uint8Array, x: number, y: number, w: number, h: number): Uint8Array;
    apply_redactions(buffer: Uint8Array, redactionsJson: string): Uint8Array;
    get_hash(buffer: Uint8Array): string;
    get_hash_with_label(buffer: Uint8Array, label: string): string;
    verify_hash_match(buffer1: Uint8Array, buffer2: Uint8Array): boolean;
    resize_image(buffer: Uint8Array, width: number, height: number): Uint8Array;
    to_grayscale(buffer: Uint8Array): Uint8Array;
    detect_pii(regionsJson: string): string;
    create_blank_image(width: number, height: number): Uint8Array;
    default(): Promise<WasmModule>;
}

// ============================================
// WORKER STATE
// ============================================

let wasmModule: WasmModule | null = null;
let isInitialized = false;

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Generate a unique ID for request tracking
 */
function generateId(): string {
    return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Send success response to main thread
 */
function sendSuccess<T>(id: string, type: string, payload: T): void {
    const response: WasmWorkerResponse<T> = {
        type: type as WasmWorkerResponse['type'],
        id,
        payload,
    };
    self.postMessage(response);
}

/**
 * Send error response to main thread
 */
function sendError(id: string, type: string, message: string): void {
    const response: WasmWorkerResponse = {
        type: type as WasmWorkerResponse['type'],
        id,
        error: message,
    };
    self.postMessage(response);
}

/**
 * Log to main thread console
 */
function log(message: string, level: 'log' | 'warn' | 'error' = 'log'): void {
    self.postMessage({
        type: 'LOG',
        level,
        message: `[WasmWorker] ${message}`,
    });
}

// ============================================
// INITIALIZATION
// ============================================

async function initializeWasm(): Promise<void> {
    log('Initializing WASM module...');
    
    try {
        // Dynamic import of WASM module
        // Vite handles this import correctly for workers
        const wasmImport = await import('../../public/wasm/wasm_core.js') as { default: () => Promise<WasmModule> };
        
        // Initialize the WASM module
        wasmModule = await wasmImport.default();
        
        // Call the init function to set up panic hook
        wasmModule.init();
        
        isInitialized = true;
        log('WASM module initialized successfully');
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        log(`Failed to initialize WASM: ${errorMessage}`, 'error');
        throw error;
    }
}

// ============================================
// MESSAGE HANDLERS
// ============================================

/**
 * Handle INIT request
 */
async function handleInit(id: string): Promise<void> {
    try {
        await initializeWasm();
        
        const moduleInfoJson = wasmModule!.get_module_info();
        const moduleInfo = JSON.parse(moduleInfoJson);
        
        const payload: InitSuccessPayload = {
            moduleInfo,
            timestamp: Date.now(),
        };
        
        sendSuccess(id, 'INIT_SUCCESS', payload);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        sendError(id, 'INIT_ERROR', message);
    }
}

/**
 * Handle LOAD_IMAGE request
 * Loads image buffer and returns RGBA pixel data + metadata
 */
async function handleLoadImage(id: string, payload: { buffer: ArrayBuffer; fileName: string }): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'LOAD_IMAGE_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { buffer, fileName } = payload;
        const uint8Buffer = new Uint8Array(buffer);
        
        log(`Loading image: ${fileName} (${buffer.byteLength} bytes)`);
        
        // Get image metadata
        const infoJson = wasmModule.get_image_info(uint8Buffer);
        const info = JSON.parse(infoJson);
        
        log(`Image decoded: ${info.width}x${info.height} (${info.format})`);
        
        // Process image to RGBA pixels
        const rgbaPixels = wasmModule.process_image(uint8Buffer, 0, 0);
        
        // Generate hash for audit trail
        const hash = wasmModule.get_hash(uint8Buffer);
        
        const resultPayload: LoadImageSuccessPayload = {
            rgbaBuffer: rgbaPixels.buffer.slice(rgbaPixels.byteOffset, rgbaPixels.byteOffset + rgbaPixels.byteLength),
            dimensions: {
                width: info.width,
                height: info.height,
            },
            info,
            hash,
        };
        
        // Transfer the buffer for efficiency (zero-copy transfer)
        self.postMessage(
            {
                type: 'LOAD_IMAGE_SUCCESS',
                id,
                payload: resultPayload,
            } as WasmWorkerResponse<LoadImageSuccessPayload>,
            [resultPayload.rgbaBuffer]
        );
        
        log(`Image loaded successfully, RGBA size: ${rgbaPixels.length} bytes`);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        log(`Load image failed: ${message}`, 'error');
        sendError(id, 'LOAD_IMAGE_ERROR', message);
    }
}

/**
 * Handle REDACT_BOX request
 * Burns a black rectangle onto the image (irreversible)
 */
async function handleRedactBox(
    id: string,
    payload: { buffer: ArrayBuffer; box: Box }
): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'REDACT_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { buffer, box } = payload;
        const uint8Buffer = new Uint8Array(buffer);
        
        log(`Redacting area: (${box.x}, ${box.y}) ${box.width}x${box.height}`);
        
        // Apply redaction
        const redactedPng = wasmModule.redact_area(
            uint8Buffer,
            box.x,
            box.y,
            box.width,
            box.height
        );
        
        // Generate hash of redacted file
        const hash = wasmModule.get_hash(redactedPng);
        
        // Calculate redacted pixels count
        const redactedPixels = box.width * box.height;
        
        const resultPayload: RedactSuccessPayload = {
            pngBuffer: redactedPng.buffer.slice(redactedPng.byteOffset, redactedPng.byteOffset + redactedPng.byteLength),
            redactedPixels,
            hash,
        };
        
        // Transfer the buffer
        self.postMessage(
            {
                type: 'REDACT_SUCCESS',
                id,
                payload: resultPayload,
            } as WasmWorkerResponse<RedactSuccessPayload>,
            [resultPayload.pngBuffer]
        );
        
        log(`Redaction complete: ${redactedPixels} pixels burned`);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        log(`Redaction failed: ${message}`, 'error');
        sendError(id, 'REDACT_ERROR', message);
    }
}

/**
 * Handle REDACT_MULTIPLE request
 * Applies multiple redactions from an array of boxes
 */
async function handleRedactMultiple(
    id: string,
    payload: { buffer: ArrayBuffer; boxes: Box[] }
): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'REDACT_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { buffer, boxes } = payload;
        const uint8Buffer = new Uint8Array(buffer);
        
        log(`Applying ${boxes.length} redactions`);
        
        // Convert boxes to JSON for WASM
        const redactionsJson = JSON.stringify(boxes.map(box => ({
            x: box.x,
            y: box.y,
            width: box.width,
            height: box.height,
            page_index: box.pageIndex || 0,
            redaction_type: 'manual',
        })));
        
        // Apply all redactions
        const redactedPng = wasmModule.apply_redactions(uint8Buffer, redactionsJson);
        
        // Generate hash
        const hash = wasmModule.get_hash(redactedPng);
        
        // Calculate total redacted pixels
        const redactedPixels = boxes.reduce((sum, box) => sum + (box.width * box.height), 0);
        
        const resultPayload: RedactSuccessPayload = {
            pngBuffer: redactedPng.buffer.slice(redactedPng.byteOffset, redactedPng.byteOffset + redactedPng.byteLength),
            redactedPixels,
            hash,
        };
        
        self.postMessage(
            {
                type: 'REDACT_SUCCESS',
                id,
                payload: resultPayload,
            } as WasmWorkerResponse<RedactSuccessPayload>,
            [resultPayload.pngBuffer]
        );
        
        log(`Multiple redactions complete: ${redactedPixels} total pixels burned`);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        log(`Multiple redaction failed: ${message}`, 'error');
        sendError(id, 'REDACT_ERROR', message);
    }
}

/**
 * Handle GET_HASH request
 * Generates SHA-256 hash of the buffer
 */
async function handleGetHash(
    id: string,
    payload: { buffer: ArrayBuffer; label?: string }
): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'HASH_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { buffer, label } = payload;
        const uint8Buffer = new Uint8Array(buffer);
        
        const hash = label
            ? wasmModule.get_hash_with_label(uint8Buffer, label)
            : wasmModule.get_hash(uint8Buffer);
        
        const resultPayload: HashResultPayload = {
            hash,
            label,
        };
        
        sendSuccess(id, 'HASH_RESULT', resultPayload);
        
        log(`Hash computed: ${hash.substring(0, 16)}...`);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        sendError(id, 'HASH_ERROR', message);
    }
}

/**
 * Handle GET_IMAGE_INFO request
 */
async function handleGetImageInfo(id: string, payload: { buffer: ArrayBuffer }): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'IMAGE_INFO_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { buffer } = payload;
        const uint8Buffer = new Uint8Array(buffer);
        
        const infoJson = wasmModule.get_image_info(uint8Buffer);
        const info = JSON.parse(infoJson);
        
        const resultPayload: ImageInfoResultPayload = { info };
        
        sendSuccess(id, 'IMAGE_INFO_RESULT', resultPayload);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        sendError(id, 'IMAGE_INFO_ERROR', message);
    }
}

/**
 * Handle RESIZE_IMAGE request
 */
async function handleResizeImage(
    id: string,
    payload: { buffer: ArrayBuffer; newWidth: number; newHeight: number }
): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'RESIZE_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { buffer, newWidth, newHeight } = payload;
        const uint8Buffer = new Uint8Array(buffer);
        
        log(`Resizing image to ${newWidth}x${newHeight}`);
        
        const resizedPng = wasmModule.resize_image(uint8Buffer, newWidth, newHeight);
        
        const resultPayload: ResizeSuccessPayload = {
            pngBuffer: resizedPng.buffer.slice(resizedPng.byteOffset, resizedPng.byteOffset + resizedPng.byteLength),
            newDimensions: { width: newWidth, height: newHeight },
        };
        
        self.postMessage(
            {
                type: 'RESIZE_SUCCESS',
                id,
                payload: resultPayload,
            } as WasmWorkerResponse<ResizeSuccessPayload>,
            [resultPayload.pngBuffer]
        );
        
        log('Image resized successfully');
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        sendError(id, 'RESIZE_ERROR', message);
    }
}

/**
 * Handle TO_GRAYSCALE request
 */
async function handleToGrayscale(id: string, payload: { buffer: ArrayBuffer }): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'GRAYSCALE_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { buffer } = payload;
        const uint8Buffer = new Uint8Array(buffer);
        
        log('Converting to grayscale');
        
        const grayscalePng = wasmModule.to_grayscale(uint8Buffer);
        
        const resultPayload: GrayscaleSuccessPayload = {
            pngBuffer: grayscalePng.buffer.slice(grayscalePng.byteOffset, grayscalePng.byteOffset + grayscalePng.byteLength),
        };
        
        self.postMessage(
            {
                type: 'GRAYSCALE_SUCCESS',
                id,
                payload: resultPayload,
            } as WasmWorkerResponse<GrayscaleSuccessPayload>,
            [resultPayload.pngBuffer]
        );
        
        log('Grayscale conversion complete');
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        sendError(id, 'GRAYSCALE_ERROR', message);
    }
}

/**
 * Handle DETECT_PII request
 */
async function handleDetectPii(id: string, payload: { regionsJson: string }): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'PII_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const { regionsJson } = payload;
        
        log('Detecting PII in text regions');
        
        const matchesJson = wasmModule.detect_pii(regionsJson);
        const matches = JSON.parse(matchesJson);
        
        const resultPayload: PiiResultPayload = {
            matches,
            count: matches.length,
        };
        
        sendSuccess(id, 'PII_RESULT', resultPayload);
        
        log(`PII detection complete: ${matches.length} matches found`);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        sendError(id, 'PII_ERROR', message);
    }
}

/**
 * Handle GET_MODULE_INFO request
 */
async function handleGetModuleInfo(id: string): Promise<void> {
    if (!isInitialized || !wasmModule) {
        sendError(id, 'MODULE_INFO_ERROR', 'WASM module not initialized');
        return;
    }
    
    try {
        const infoJson = wasmModule.get_module_info();
        const info = JSON.parse(infoJson);
        
        const resultPayload: ModuleInfoResultPayload = { info };
        
        sendSuccess(id, 'MODULE_INFO_RESULT', resultPayload);
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        sendError(id, 'MODULE_INFO_ERROR', message);
    }
}

// ============================================
// MESSAGE HANDLER
// ============================================

self.onmessage = async (event: MessageEvent<WasmWorkerMessage>) => {
    const { type, id, payload } = event.data;
    
    log(`Received message: ${type} (id: ${id})`);
    
    switch (type) {
        case 'INIT':
            await handleInit(id);
            break;
            
        case 'LOAD_IMAGE':
            await handleLoadImage(id, payload as { buffer: ArrayBuffer; fileName: string });
            break;
            
        case 'REDACT_BOX':
            await handleRedactBox(id, payload as { buffer: ArrayBuffer; box: Box });
            break;
            
        case 'REDACT_MULTIPLE':
            await handleRedactMultiple(id, payload as { buffer: ArrayBuffer; boxes: Box[] });
            break;
            
        case 'GET_HASH':
            await handleGetHash(id, payload as { buffer: ArrayBuffer; label?: string });
            break;
            
        case 'GET_IMAGE_INFO':
            await handleGetImageInfo(id, payload as { buffer: ArrayBuffer });
            break;
            
        case 'RESIZE_IMAGE':
            await handleResizeImage(id, payload as { buffer: ArrayBuffer; newWidth: number; newHeight: number });
            break;
            
        case 'TO_GRAYSCALE':
            await handleToGrayscale(id, payload as { buffer: ArrayBuffer });
            break;
            
        case 'DETECT_PII':
            await handleDetectPii(id, payload as { regionsJson: string });
            break;
            
        case 'GET_MODULE_INFO':
            await handleGetModuleInfo(id);
            break;
            
        case 'TERMINATE':
            log('Terminating worker');
            self.close();
            break;
            
        default:
            sendError(id, 'PROCESSING_ERROR', `Unknown message type: ${type}`);
    }
};

// ============================================
// ERROR HANDLING
// ============================================

self.onerror = (error: ErrorEvent) => {
    log(`Worker error: ${error.message}`, 'error');
    return false;
};

self.onunhandledrejection = (event: PromiseRejectionEvent) => {
    log(`Unhandled promise rejection: ${event.reason}`, 'error');
};

// Signal that worker is ready to receive messages
log('Worker thread started, waiting for INIT command');
